name: backup_to_dropbox
description: A appwrite dart cloud function to backup collection data to dropbox
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"
  #sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  dart_appwrite: ^1.0.1
  path: ^1.8.0
  csv: ^5.0.0

dev_dependencies:
  lints: ^1.0.0
